### ISSUE TITLE
Add support for customizing input metadata forms

### ISSUE THREAD

**Issue by jrgriffiniii** [jrgriffiniii/dataspace-jspui#10] opened 2020-06-16 15:08 UTC
These are files which customize the metadata captured for new item submissions. Please see https://wiki.lyrasis.org/display/DSDOC5x/Submission+User+Interface for reference.

**Comment by kmcelwee** [comment] 2021-04-20 20:12
This is a duplicate of https://github.com/pulibrary/dspace-development/issues/273

**Closed as completed by kmcelwee** 2021-04-20 20:12 UTC
Labels: duplicate, enhancement
